# Generated by Django 4.2.13 on 2024-06-22 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_artwork_price_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 13, 28, 4, 639451, tzinfo=datetime.timezone.utc)),
        ),
    ]
