# Generated by Django 4.2.13 on 2024-06-22 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_artwork_auction_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'is_seller': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 15, 50, 35, 906482, tzinfo=datetime.timezone.utc)),
        ),
    ]
