# Generated by Django 4.2.13 on 2024-06-22 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_artwork_auction_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 16, 35, 43, 727183, tzinfo=datetime.timezone.utc)),
        ),
    ]
