# Generated by Django 4.2.13 on 2024-06-23 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_is_seller_alter_artwork_auction_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notify_auction_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notify_outbid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 9, 21, 52, 799134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='app/static/artwork_images', verbose_name='Attachment'),
        ),
    ]
