# Generated by Django 4.2.13 on 2024-06-23 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_notify_auction_end_customer_notify_outbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 11, 40, 17, 635444, tzinfo=datetime.timezone.utc)),
        ),
    ]
