# Generated by Django 4.2.13 on 2024-06-25 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_artwork_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 13, 36, 2, 509987, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
