# Generated by Django 4.2.13 on 2024-07-04 13:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_artwork_auction_end'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='AppUser',
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 13, 41, 8, 464938, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
