# Generated by Django 4.2.13 on 2024-07-04 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_customer_appuser_alter_appuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='notify_auction_end',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='notify_outbid',
        ),
        migrations.AddField(
            model_name='artwork',
            name='sold_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SoldArtworks', to='app.appuser'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 22, 59, 42, 690579, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
