# Generated by Django 4.2.13 on 2024-07-05 16:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_appuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 16, 59, 25, 303346, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
