# Generated by Django 4.2.13 on 2024-07-05 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_bid_date_posted_alter_artwork_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 20, 33, 58, 405751, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
