# Generated by Django 4.2.13 on 2024-07-05 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_artist_birthday_alter_artwork_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 21, 47, 5, 310320, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
